import { createServer } from 'http'
import next from 'next'
import { Server } from 'socket.io'

const dev = process.env.NODE_ENV !== 'production'
const hostname = '0.0.0.0'
const port = 3000

const app = next({ dev, hostname, port })
const handle = app.getRequestHandler()

app.prepare().then(() => {
  const httpServer = createServer((req, res) => {
    const parsedUrl = new URL(req.url, `http://${req.headers.host || 'localhost'}`)
    handle(req, res, parsedUrl)
  })

  // ─── Socket.IO Setup ────────────────────────────────────────────────────────
  const io = new Server(httpServer, {
    path: '/socket.io/',
    cors: {
      origin: '*',
      methods: ['GET', 'POST'],
    },
    pingTimeout: 10000,
    pingInterval: 5000,
  })

  // ─── In-Memory State ────────────────────────────────────────────────────────

  const rooms = new Map()
  const socketRoomMap = new Map()
  let globalJoinCounter = 0

  // ─── Helpers ────────────────────────────────────────────────────────────────

  const ROOM_CODE_CHARS = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'

  function generateRoomCode() {
    let code = ''
    for (let i = 0; i < 6; i++) {
      code += ROOM_CODE_CHARS[Math.floor(Math.random() * ROOM_CODE_CHARS.length)]
    }
    while (rooms.has(code)) {
      code = ''
      for (let i = 0; i < 6; i++) {
        code += ROOM_CODE_CHARS[Math.floor(Math.random() * ROOM_CODE_CHARS.length)]
      }
    }
    return code
  }

  function playersToArray(players) {
    return Array.from(players.values()).sort((a, b) => a.joinOrder - b.joinOrder)
  }

  function findNextHost(players, excludeId) {
    let earliest
    for (const player of players.values()) {
      if (excludeId && player.id === excludeId) continue
      if (!earliest || player.joinOrder < earliest.joinOrder) {
        earliest = player
      }
    }
    return earliest
  }

  function getPublicRoomsList() {
    const list = []
    for (const room of rooms.values()) {
      if (room.roomType === 'عامة' && room.status === 'waiting' && room.players.size > 0) {
        list.push({
          roomCode: room.roomCode,
          roomType: room.roomType,
          hasPassword: !!room.password,
          hostName: room.hostName,
          playerCount: room.players.size,
          maxPlayers: room.settings.maxPlayers,
          settings: room.settings,
          status: room.status,
        })
      }
    }
    return list
  }

  function calculateScore(isCorrect, timeTaken, roundTimeSeconds) {
    if (!isCorrect) return 0
    const base = 10
    const speedBonus = Math.max(0, 5 * (1 - timeTaken / roundTimeSeconds))
    return Math.round((base + speedBonus) * 10) / 10
  }

  // ─── No Fallback Content ────────────────────────────────────────────────────
  // ALL content is dynamically generated by AI. No static/fallback content.

  // ─── fetchGameContent ──────────────────────────────────────────────────────

  async function fetchGameContent(gameType, difficulty, roomCode, playerNames, previousTopics) {
    // Emit real progress: searching for inspiration
    io.to(roomCode).emit('content-progress', { step: 'searching', text: 'جاري البحث عن مصادر إلهام...' })

    // Emit progress: generating content after search
    io.to(roomCode).emit('content-progress', { step: 'generating', text: 'جاري توليد المحتوى بالذكاء الاصطناعي...' })

    // Emit progress: preparing before fetch
    io.to(roomCode).emit('content-progress', { step: 'preparing', text: 'جاري تجهيز الساحة...' })

    // Retry logic - all content is AI generated, no fallback
    const MAX_RETRIES = 3
    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      const controller = new AbortController()
      const timeout = setTimeout(() => controller.abort(), 45000)

      try {
        io.to(roomCode).emit('content-progress', {
          step: 'generating',
          text: attempt === 1
            ? 'جاري توليد المحتوى بالذكاء الاصطناعي...'
            : `محاولة ${attempt} من ${MAX_RETRIES} - جاري إعادة توليد المحتوى...`
        })

        const response = await fetch('http://localhost:3000/api/generate-content', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ gameType, difficulty, playerNames, previousTopics }),
          signal: controller.signal,
        })

        clearTimeout(timeout)

        if (!response.ok) {
          console.error(`[fetchGameContent] Attempt ${attempt}: API returned ${response.status}`)
          continue
        }

        const data = await response.json()
        if (!data.content) {
          console.error(`[fetchGameContent] Attempt ${attempt}: No content in API response`)
          continue
        }

        io.to(roomCode).emit('content-progress', { step: 'ready', text: 'المحتوى جاهز! استعد للقتال!' })
        return data.content
      } catch (err) {
        clearTimeout(timeout)
        if (err.name === 'AbortError') {
          console.error(`[fetchGameContent] Attempt ${attempt}: Timeout after 45s for room ${roomCode}`)
        } else {
          console.error(`[fetchGameContent] Attempt ${attempt}: Error for room ${roomCode}:`, err.message)
        }
        if (attempt < MAX_RETRIES) {
          io.to(roomCode).emit('content-progress', {
            step: 'retrying',
            text: `فشل المحاولة ${attempt}... جاري إعادة المحاولة...`
          })
          await new Promise(r => setTimeout(r, 1000 * attempt))
        }
      }
    }

    console.error(`[fetchGameContent] All ${MAX_RETRIES} attempts failed for room ${roomCode}`)
    throw new Error('فشل في توليد المحتوى بعد محاولات متعددة. يرجى المحاولة مرة أخرى.')
  }

  // ─── broadcastPublicRooms ───────────────────────────────────────────────────

  function broadcastPublicRooms() {
    const list = getPublicRoomsList()
    io.emit('public-rooms-update', { rooms: list })
  }

  // ─── deleteRoom ─────────────────────────────────────────────────────────────

  function deleteRoom(roomCode) {
    const room = rooms.get(roomCode)
    if (!room) return

    for (const [socketId, code] of socketRoomMap.entries()) {
      if (code === roomCode) {
        socketRoomMap.delete(socketId)
      }
    }

    rooms.delete(roomCode)
    console.log(`[delete-room] Room ${roomCode} deleted`)
    broadcastPublicRooms()
  }

  // ─── calculateRoundScores ───────────────────────────────────────────────────

  function calculateRoundScores(room, roundIndex) {
    const scores = []

    for (const [playerId, player] of room.players.entries()) {
      const playerRoundsAnswers = room.playerAnswers.get(playerId)
      const roundAnswers = playerRoundsAnswers?.get(roundIndex)
      const roundContent = room.rounds[roundIndex]

      let roundScore = 0
      let correctAnswers = 0
      const totalQuestions = roundContent?.content.questions.length || 0

      if (roundAnswers && roundContent) {
        for (const [qIndex, answer] of roundAnswers.entries()) {
          const question = roundContent.content.questions[qIndex]
          if (question) {
            const isCorrect = question.correctAnswer === answer.answerIndex
            const points = calculateScore(isCorrect, answer.timeTaken, room.roundTimerSeconds)
            roundScore += points
            if (isCorrect) correctAnswers++
          }
        }
      }

      scores.push({
        playerId,
        playerName: player.name,
        score: roundScore,
        correctAnswers,
        totalQuestions,
      })
    }

    return scores.sort((a, b) => b.score - a.score)
  }

  // ─── removePlayerFromRoom ───────────────────────────────────────────────────

  function removePlayerFromRoom(socketId, reason) {
    const roomCode = socketRoomMap.get(socketId)
    if (!roomCode) return

    const room = rooms.get(roomCode)
    if (!room) {
      socketRoomMap.delete(socketId)
      return
    }

    const player = room.players.get(socketId)
    const playerName = player?.name || socketId

    // Remove player entirely
    room.players.delete(socketId)
    room.playerAnswers.delete(socketId)
    socketRoomMap.delete(socketId)

    // If room is now empty, delete it immediately
    if (room.players.size === 0) {
      deleteRoom(roomCode)
      console.log(`[removePlayer] ${playerName} left room ${roomCode}. Room deleted (empty).`)
      return
    }

    // If the removed player was the host, transfer host to the earliest remaining player
    if (room.hostId === socketId) {
      const newHost = findNextHost(room.players)
      if (newHost) {
        room.hostId = newHost.id
        room.hostName = newHost.name
        newHost.isHost = true
        io.to(roomCode).emit('host-changed', {
          newHostId: newHost.id,
          newHostName: newHost.name,
          oldHostName: playerName,
          players: playersToArray(room.players),
        })
      }
    }

    // Notify remaining players
    if (reason === 'leave') {
      io.to(roomCode).emit('player-left', {
        playerId: socketId,
        playerName,
        players: playersToArray(room.players),
      })
    } else {
      io.to(roomCode).emit('player-disconnected', {
        playerId: socketId,
        playerName,
        players: playersToArray(room.players),
      })
    }

    console.log(`[removePlayer] ${playerName} ${reason === 'leave' ? 'left' : 'disconnected from'} room ${roomCode}. Remaining: ${room.players.size}`)

    broadcastPublicRooms()
  }

  // ─── Round Management ───────────────────────────────────────────────────────

  async function generateRemainingRounds(roomCode, totalRounds, gameType, difficulty, playerNames) {
    const room = rooms.get(roomCode)
    if (!room) return

    for (let i = 1; i < totalRounds; i++) {
      try {
        const previousTopics = room.rounds
          .filter(r => r.content?.title)
          .map(r => r.content.title)

        const content = await fetchGameContent(gameType, difficulty, roomCode, playerNames, previousTopics)
        if (!rooms.has(roomCode)) return // Room was deleted

        room.rounds.push({
          roundNumber: i,
          content,
        })
        console.log(`[generateRemainingRounds] Generated round ${i + 1} content for room ${roomCode}`)
      } catch (err) {
        console.error(`[generateRemainingRounds] Failed to generate round ${i + 1} for room ${roomCode}:`, err)
      }
    }
  }

  function handleRoundEnd(roomCode) {
    const room = rooms.get(roomCode)
    if (!room || room.status !== 'playing') return

    const currentRound = room.currentRound
    const totalRounds = room.settings.numberOfRounds

    // Calculate per-round scores (not cumulative)
    const roundScores = calculateRoundScores(room, currentRound)
    room.roundResults.set(currentRound, roundScores)

    // Determine round winner (player with highest score in this round)
    if (roundScores.length > 0) {
      const winnerId = roundScores[0].playerId
      room.roundWinners.set(currentRound, winnerId)

      // Update player's roundWins count
      const winnerPlayer = room.players.get(winnerId)
      if (winnerPlayer) {
        winnerPlayer.roundWins++
      }
    }

    // Reset all player scores for the next round (scores are per-round, not cumulative)
    for (const player of room.players.values()) {
      player.score = 0
    }

    // Check if this was the last round
    if (currentRound >= totalRounds - 1) {
      // Game over! Send round-end first, then game-ended
      io.to(roomCode).emit('round-end', {
        roundNumber: currentRound,
        totalRounds,
        roundScores,
        roundWinner: roundScores[0] || null,
        isLastRound: true,
      })

      // Small delay before showing final results
      setTimeout(() => {
        handleGameEnd(roomCode)
      }, 3000)
      return
    }

    // Send round-end event with scores
    io.to(roomCode).emit('round-end', {
      roundNumber: currentRound,
      totalRounds,
      roundScores,
      roundWinner: roundScores[0] || null,
      isLastRound: false,
    })

    // Move to next round after a brief delay for showing round results
    setTimeout(() => {
      const r = rooms.get(roomCode)
      if (!r || r.status !== 'playing') return

      r.currentRound = currentRound + 1

      // Check if next round content is ready
      const nextRound = r.rounds[r.currentRound]
      if (!nextRound) {
        // Content not ready yet, show loading
        console.log(`[handleRoundEnd] Round ${r.currentRound + 1} content not ready for room ${roomCode}, waiting...`)
        io.to(roomCode).emit('round-loading', {
          roundNumber: r.currentRound,
          totalRounds,
        })

        // Poll for content
        const checkInterval = setInterval(() => {
          const rr = rooms.get(roomCode)
          if (!rr || rr.status !== 'playing') {
            clearInterval(checkInterval)
            return
          }
          const nextR = rr.rounds[rr.currentRound]
          if (nextR) {
            clearInterval(checkInterval)
            rr.roundStartTime = Date.now()
            rr.roundTimerSeconds = rr.settings.timePerRound * 60
            io.to(roomCode).emit('round-start', {
              roundNumber: rr.currentRound,
              totalRounds: rr.settings.numberOfRounds,
              content: nextR.content,
              timePerRound: rr.roundTimerSeconds,
            })
            console.log(`[handleRoundEnd] Delayed round ${rr.currentRound + 1} started in room ${roomCode}`)
          }
        }, 2000)

        return
      }

      // Start next round
      r.roundStartTime = Date.now()
      r.roundTimerSeconds = r.settings.timePerRound * 60

      io.to(roomCode).emit('round-start', {
        roundNumber: r.currentRound,
        totalRounds,
        content: nextRound.content,
        timePerRound: r.roundTimerSeconds,
      })

      console.log(`[handleRoundEnd] Round ${r.currentRound + 1} started in room ${roomCode}. Timer: ${r.roundTimerSeconds}s`)
    }, 5000) // 5 second delay between rounds to show round results
  }

  function handleGameEnd(roomCode) {
    const room = rooms.get(roomCode)
    if (!room) return

    room.status = 'finished'

    // Determine overall winner by round wins (not cumulative score)
    const finalResults = playersToArray(room.players)
      .sort((a, b) => b.roundWins - a.roundWins)

    // The "score" field now represents roundWins for the final results
    const scoresWithWins = finalResults.map(p => ({
      ...p,
      score: p.roundWins, // Override score with roundWins for the leaderboard
    }))

    io.to(roomCode).emit('game-ended', {
      scores: scoresWithWins,
      roundWinners: Object.fromEntries(room.roundWinners),
      roundResults: Object.fromEntries(
        Array.from(room.roundResults.entries()).map(([k, v]) => [k, v])
      ),
      totalRounds: room.settings.numberOfRounds,
    })

    console.log(`[handleGameEnd] Game ended in room ${roomCode}. Winner: ${finalResults[0]?.name} (${finalResults[0]?.roundWins} round wins)`)
    broadcastPublicRooms()
  }

  // ─── Socket.IO Connection Handler ───────────────────────────────────────────

  io.on('connection', (socket) => {
    console.log(`[connected] ${socket.id}`)

    // Send current public rooms list on connect
    socket.emit('public-rooms-update', { rooms: getPublicRoomsList() })

    // ── get-public-rooms ─────────────────────────────────────────────────
    socket.on('get-public-rooms', () => {
      socket.emit('public-rooms-update', { rooms: getPublicRoomsList() })
    })

    // ── rejoin-room ──────────────────────────────────────────────────────
    socket.on('rejoin-room', (data) => {
      const { roomCode, playerName } = data

      if (!roomCode || !playerName) {
        socket.emit('rejoin-failed', { message: 'بيانات النظام غير كاملة' })
        return
      }

      const room = rooms.get(roomCode.toUpperCase())
      if (!room) {
        socket.emit('rejoin-failed', { message: 'الغرفة لم تعد موجودة' })
        return
      }

      // Find the player by name in the room
      let existingPlayer
      let existingPlayerId
      for (const [id, player] of room.players.entries()) {
        if (player.name === playerName.trim()) {
          existingPlayer = player
          existingPlayerId = id
          break
        }
      }

      if (!existingPlayer || !existingPlayerId) {
        socket.emit('rejoin-failed', { message: 'أنت لست في هذه الغرفة' })
        return
      }

      // Update the player's ID to the new socket ID
      const oldId = existingPlayerId
      existingPlayer.id = socket.id

      // Move from old key to new key in players map
      room.players.delete(oldId)
      room.players.set(socket.id, existingPlayer)

      // Move answers too
      const oldAnswers = room.playerAnswers.get(oldId)
      if (oldAnswers) {
        room.playerAnswers.delete(oldId)
        room.playerAnswers.set(socket.id, oldAnswers)
      }

      // Update host ID if needed
      if (room.hostId === oldId) {
        room.hostId = socket.id
      }

      // Set up new socket mapping
      socketRoomMap.set(socket.id, roomCode)
      socket.join(roomCode)

      // Send the full room/game state to the rejoining player
      const rejoinData = {
        roomCode,
        players: playersToArray(room.players),
        settings: room.settings,
        roomType: room.roomType,
        hasPassword: !!room.password,
        isHost: existingPlayer.isHost,
        status: room.status,
        currentRound: room.currentRound,
      }

      // If game is in progress, send current round content and progress
      if (room.status === 'playing' && room.rounds.length > 0) {
        const currentRoundContent = room.rounds[room.currentRound]
        if (currentRoundContent) {
          rejoinData.gameContent = currentRoundContent.content
          rejoinData.currentRound = room.currentRound
          rejoinData.totalRounds = room.settings.numberOfRounds
          rejoinData.answers = {}
          const playerAnswersForRounds = room.playerAnswers.get(socket.id)
          if (playerAnswersForRounds) {
            const roundAnswers = playerAnswersForRounds.get(room.currentRound)
            if (roundAnswers) {
              for (const [qIndex, answer] of roundAnswers.entries()) {
                rejoinData.answers[qIndex] = answer.answerIndex
              }
            }
          }
          // Calculate remaining time
          if (room.roundStartTime) {
            const elapsed = Math.floor((Date.now() - room.roundStartTime) / 1000)
            rejoinData.timeLeft = Math.max(0, room.roundTimerSeconds - elapsed)
          }
        }
      }

      // If game is finished, send final results
      if (room.status === 'finished') {
        const finalScores = playersToArray(room.players).sort((a, b) => b.score - a.score)
        rejoinData.scores = finalScores
        rejoinData.totalRounds = room.settings.numberOfRounds
        rejoinData.roundWinners = Object.fromEntries(room.roundWinners)
        rejoinData.roundResults = Object.fromEntries(
          Array.from(room.roundResults.entries()).map(([k, v]) => [k, v])
        )
      }

      socket.emit('rejoin-success', rejoinData)

      // Notify other players that this player reconnected
      socket.to(roomCode).emit('player-reconnected', {
        playerId: socket.id,
        playerName: existingPlayer.name,
        players: playersToArray(room.players),
      })

      broadcastPublicRooms()

      console.log(`[rejoin-room] ${playerName} (${socket.id}) rejoined room ${roomCode} (was ${oldId})`)
    })

    // ── leave-room ───────────────────────────────────────────────────────
    socket.on('leave-room', () => {
      const roomCode = socketRoomMap.get(socket.id)
      if (!roomCode) return

      // Leave the Socket.io room FIRST so they don't receive any more events
      socket.leave(roomCode)
      removePlayerFromRoom(socket.id, 'leave')
    })

    // ── create-game ──────────────────────────────────────────────────────
    socket.on('create-game', (data) => {
      const { playerName, settings, roomType, password } = data

      if (!playerName || playerName.trim().length === 0) {
        socket.emit('game-error', { message: 'اسم اللاعب مطلوب' })
        return
      }

      // Validate rounds rule: 2 players can't play 2 rounds, 3 players can't play 3 rounds
      if ((settings.maxPlayers === 2 && settings.numberOfRounds === 2) || (settings.maxPlayers === 3 && settings.numberOfRounds === 3)) {
        socket.emit('game-error', { message: 'عدد الجولات لا يمكن أن يساوي عدد اللاعبين عند 2 أو 3 لاعبين' })
        return
      }

      // Cap rounds at 20
      if (settings.numberOfRounds > 20) {
        settings.numberOfRounds = 20
      }

      const roomCode = generateRoomCode()

      const player = {
        id: socket.id,
        name: playerName.trim(),
        score: 0,
        isHost: true,
        isReady: true,
        joinOrder: globalJoinCounter++,
        roundWins: 0,
      }

      const playersMap = new Map()
      playersMap.set(socket.id, player)

      const room = {
        roomCode,
        roomType: roomType || 'عامة',
        password: (roomType === 'خاصة' && password?.trim()) ? password.trim() : null,
        hostId: socket.id,
        hostName: playerName.trim(),
        settings,
        players: playersMap,
        rounds: [],
        status: 'waiting',
        currentRound: 0,
        playerAnswers: new Map(),
        roundStartTime: null,
        roundTimerSeconds: settings.timePerRound * 60,
        roundResults: new Map(),
        roundWinners: new Map(),
      }

      rooms.set(roomCode, room)
      socketRoomMap.set(socket.id, roomCode)
      socket.join(roomCode)

      socket.emit('game-created', {
        roomCode,
        roomType: room.roomType,
        hasPassword: !!room.password,
      })

      if (room.roomType === 'عامة') {
        broadcastPublicRooms()
      }

      console.log(`[create-game] Room ${roomCode} (${roomType}${room.password ? ' +password' : ''}) created by ${playerName} (${socket.id})`)
    })

    // ── join-game ────────────────────────────────────────────────────────
    socket.on('join-game', (data) => {
      const { roomCode, playerName, password } = data

      if (!roomCode || !playerName || playerName.trim().length === 0) {
        socket.emit('game-error', { message: 'رمز الغرفة واسم اللاعب مطلوبان' })
        return
      }

      const room = rooms.get(roomCode.toUpperCase())
      if (!room) {
        socket.emit('game-error', { message: 'الغرفة غير موجودة أو تم حذفها' })
        return
      }

      if (room.players.size === 0) {
        socket.emit('game-error', { message: 'الغرفة غير موجودة أو تم حذفها' })
        broadcastPublicRooms()
        return
      }

      if (room.status !== 'waiting') {
        socket.emit('game-error', { message: 'اللعبة قد بدأت بالفعل' })
        return
      }

      if (room.players.size >= room.settings.maxPlayers) {
        socket.emit('game-error', { message: 'الغرفة ممتلئة' })
        return
      }

      // Check password for private rooms
      if (room.password && room.password !== password) {
        socket.emit('game-error', { message: 'كلمة السر غلط' })
        return
      }

      // Check if player name is already taken
      const nameTaken = Array.from(room.players.values()).some(
        (p) => p.name === playerName.trim()
      )
      if (nameTaken) {
        socket.emit('game-error', { message: 'اسم اللاعب مستخدم بالفعل في هذه الغرفة' })
        return
      }

      const player = {
        id: socket.id,
        name: playerName.trim(),
        score: 0,
        isHost: false,
        isReady: false,
        joinOrder: globalJoinCounter++,
        roundWins: 0,
      }

      room.players.set(socket.id, player)
      socketRoomMap.set(socket.id, roomCode)
      socket.join(roomCode)

      // Send game info to the joiner
      socket.emit('game-joined', {
        roomCode,
        players: playersToArray(room.players),
        settings: room.settings,
        roomType: room.roomType,
        hasPassword: !!room.password,
      })

      // Notify others in the room
      socket.to(roomCode).emit('player-joined', {
        player,
        players: playersToArray(room.players),
      })

      broadcastPublicRooms()

      console.log(`[join-game] ${playerName} (${socket.id}) joined room ${roomCode}`)
    })

    // ── start-game ───────────────────────────────────────────────────────
    socket.on('start-game', async (data) => {
      const { roomCode } = data
      const room = rooms.get(roomCode?.toUpperCase())

      console.log(`[start-game] Request from ${socket.id}, roomCode: ${roomCode}, room found: ${!!room}`)

      if (!room) {
        socket.emit('game-error', { message: 'الغرفة غير موجودة' })
        return
      }

      if (room.hostId !== socket.id) {
        socket.emit('game-error', { message: 'فقط المضيف يمكنه بدء اللعبة' })
        return
      }

      if (room.players.size < 2) {
        socket.emit('game-error', { message: 'يجب أن يكون هناك لاعبان على الأقل' })
        return
      }

      if (room.status !== 'waiting') {
        socket.emit('game-error', { message: 'اللعبة قد بدأت بالفعل' })
        return
      }

      // Update room status
      room.status = 'playing'
      room.currentRound = 0

      // Reset all player scores and round wins for the new game
      for (const player of room.players.values()) {
        player.score = 0
        player.roundWins = 0
      }
      room.roundResults.clear()
      room.roundWinners.clear()

      // Notify all players that game is starting
      io.to(roomCode).emit('game-starting', {})
      // Emit first progress step
      io.to(roomCode).emit('content-progress', { step: 'preparing', text: 'جاري تجهيز الساحة...' })

      // Update public rooms (game started, no longer in waiting)
      broadcastPublicRooms()

      // Get player names for content tracking
      const playerNames = playersToArray(room.players).map(p => p.name)

      // Safety timeout: ensure the game never gets permanently stuck on the loading screen
      // If content generation takes more than 90s total, send error and return to lobby
      const safetyTimeout = setTimeout(() => {
        const r = rooms.get(roomCode)
        if (r && r.status === 'playing' && r.rounds.length === 0) {
          console.error(`[start-game] Safety timeout triggered for room ${roomCode} after 90s`)
          r.status = 'waiting'
          r.rounds = []
          io.to(roomCode).emit('game-error', {
            message: 'فشل في توليد محتوى اللعبة. يرجى المحاولة مرة أخرى.',
          })
          broadcastPublicRooms()
        }
      }, 90000)

      // Generate content for all rounds
      try {
        // Generate first round content
        console.log(`[start-game] Generating first round content for room ${roomCode}...`)
        io.to(roomCode).emit('content-progress', { step: 'generating', text: 'جاري توليد الأسئلة والمحتوى...' })

        const firstRoundContent = await fetchGameContent(
          room.settings.gameType,
          room.settings.difficulty,
          roomCode,
          playerNames,
          [] // No previous topics for first round
        )
        room.rounds.push({
          roundNumber: 0,
          content: firstRoundContent,
        })

        // Initialize answer maps for all players
        for (const playerId of room.players.keys()) {
          if (!room.playerAnswers.has(playerId)) {
            room.playerAnswers.set(playerId, new Map())
          }
        }

        // Set round timer
        room.roundTimerSeconds = room.settings.timePerRound * 60
        room.roundStartTime = Date.now()

        // Emit ready progress
        io.to(roomCode).emit('content-progress', { step: 'ready', text: 'استعد للقتال!' })

        // Send first round content to all players
        io.to(roomCode).emit('round-start', {
          roundNumber: 0,
          totalRounds: room.settings.numberOfRounds,
          content: firstRoundContent,
          timePerRound: room.roundTimerSeconds,
        })

        console.log(`[start-game] Round 1 content sent to room ${roomCode}. Timer: ${room.roundTimerSeconds}s`)

        // Pre-generate remaining rounds in the background
        generateRemainingRounds(roomCode, room.settings.numberOfRounds, room.settings.gameType, room.settings.difficulty, playerNames)
        // Clear safety timeout since content was generated successfully
        clearTimeout(safetyTimeout)
      } catch (err) {
        console.error(`[start-game] Failed to generate content for room ${roomCode}:`, err)
        clearTimeout(safetyTimeout)
        room.status = 'waiting'
        room.rounds = []
        io.to(roomCode).emit('game-error', {
          message: 'فشل في توليد محتوى اللعبة. يرجى المحاولة مرة أخرى.',
        })
        broadcastPublicRooms()
      }
    })

    // ── submit-answer ────────────────────────────────────────────────────
    socket.on('submit-answer', (data) => {
      const { roomCode, roundNumber, questionIndex, answerIndex, timeTaken } = data
      const room = rooms.get(roomCode?.toUpperCase())

      if (!room) {
        socket.emit('game-error', { message: 'الغرفة غير موجودة' })
        return
      }

      if (room.status !== 'playing') {
        socket.emit('game-error', { message: 'اللعبة ليست قيد التشغيل' })
        return
      }

      const player = room.players.get(socket.id)
      if (!player) {
        socket.emit('game-error', { message: 'أنت لست في هذه الغرفة' })
        return
      }

      // Make sure we're on the right round
      if (roundNumber !== room.currentRound) {
        return // Ignore answers for wrong rounds
      }

      const roundContent = room.rounds[roundNumber]
      if (!roundContent) return

      // Get or create the player's answer maps
      let playerRoundsAnswers = room.playerAnswers.get(socket.id)
      if (!playerRoundsAnswers) {
        playerRoundsAnswers = new Map()
        room.playerAnswers.set(socket.id, playerRoundsAnswers)
      }

      let roundAnswers = playerRoundsAnswers.get(roundNumber)
      if (!roundAnswers) {
        roundAnswers = new Map()
        playerRoundsAnswers.set(roundNumber, roundAnswers)
      }

      // Prevent duplicate answers for the same question
      if (roundAnswers.has(questionIndex)) {
        return
      }

      // Record the answer
      roundAnswers.set(questionIndex, { answerIndex, timeTaken })

      // Calculate score for this answer (per-round score, not cumulative)
      const question = roundContent.content.questions[questionIndex]
      if (question) {
        const isCorrect = question.correctAnswer === answerIndex
        const points = calculateScore(
          isCorrect,
          timeTaken,
          room.roundTimerSeconds
        )
        player.score += points
      }

      // Check if this player has answered all questions in this round
      const totalQuestions = roundContent.content.questions.length
      const playerAnsweredAll = roundAnswers.size >= totalQuestions

      // Notify the player of their answer status
      socket.emit('answer-confirmed', {
        questionIndex,
        answerIndex,
        roundNumber,
        playerAnsweredAll,
      })

      // Check if ALL players have answered all questions in this round
      const allPlayersAnsweredAll = Array.from(room.players.keys()).every((playerId) => {
        const pAnswers = room.playerAnswers.get(playerId)
        if (!pAnswers) return false
        const rAnswers = pAnswers.get(roundNumber)
        if (!rAnswers) return false
        return rAnswers.size >= totalQuestions
      })

      if (allPlayersAnsweredAll) {
        // All players finished this round
        handleRoundEnd(roomCode)
      }
    })

    // ── round-time-up ────────────────────────────────────────────────────
    socket.on('round-time-up', (data) => {
      const { roomCode, roundNumber } = data
      const room = rooms.get(roomCode?.toUpperCase())
      if (!room || room.status !== 'playing') return
      if (roundNumber !== room.currentRound) return

      // Check if round time has actually expired
      if (room.roundStartTime) {
        const elapsed = Math.floor((Date.now() - room.roundStartTime) / 1000)
        if (elapsed >= room.roundTimerSeconds - 2) { // Allow 2s buffer for network delay
          handleRoundEnd(roomCode)
        }
      }
    })

    // ── surrender ────────────────────────────────────────────────────────
    socket.on('surrender', () => {
      const roomCode = socketRoomMap.get(socket.id)
      if (!roomCode) return

      const room = rooms.get(roomCode)
      if (!room) return

      const player = room.players.get(socket.id)
      const playerName = player?.name || socket.id

      // Leave the socket.io room
      socket.leave(roomCode)
      removePlayerFromRoom(socket.id, 'leave')

      // Notify the player that they successfully surrendered
      socket.emit('surrender-confirmed', { roomCode })

      // If game is playing and only 1 player left, auto-end the game
      const updatedRoom = rooms.get(roomCode)
      if (updatedRoom && updatedRoom.status === 'playing' && updatedRoom.players.size === 1) {
        // Notify the remaining player that they won because the opponent left
        const remainingPlayer = Array.from(updatedRoom.players.values())[0]
        io.to(roomCode).emit('opponent-left-game', {
          leftPlayerName: playerName,
          winnerName: remainingPlayer?.name,
        })
        // End the game immediately
        handleGameEnd(roomCode)
      } else if (updatedRoom && updatedRoom.status === 'playing' && updatedRoom.players.size === 0) {
        deleteRoom(roomCode)
      }
    })

    // ── disconnect ───────────────────────────────────────────────────────
    socket.on('disconnect', () => {
      const roomCode = socketRoomMap.get(socket.id)
      if (!roomCode) {
        console.log(`[disconnect] ${socket.id} (not in any room)`)
        return
      }

      // Get player name BEFORE removing them
      const room = rooms.get(roomCode)
      const player = room?.players.get(socket.id)
      const disconnectedPlayerName = player?.name || socket.id

      console.log(`[disconnect] ${socket.id} disconnected from room ${roomCode}`)

      // Leave the socket.io room
      socket.leave(roomCode)

      // Remove player immediately - no grace period
      removePlayerFromRoom(socket.id, 'disconnect')

      // If game is playing and only 1 player left, notify them and auto-end the game
      const updatedRoom = rooms.get(roomCode)
      if (updatedRoom && updatedRoom.status === 'playing' && updatedRoom.players.size === 1) {
        const remainingPlayer = Array.from(updatedRoom.players.values())[0]
        io.to(roomCode).emit('opponent-left-game', {
          leftPlayerName: disconnectedPlayerName,
          winnerName: remainingPlayer?.name,
        })
        // End the game immediately - only one player left
        handleGameEnd(roomCode)
      } else if (updatedRoom && updatedRoom.status === 'playing' && updatedRoom.players.size === 0) {
        // No players left - delete room
        deleteRoom(roomCode)
      }
    })

    socket.on('error', (error) => {
      console.error(`[error] Socket error (${socket.id}):`, error)
    })
  })

  // ─── Start Server ───────────────────────────────────────────────────────────

  httpServer.listen(port, hostname, () => {
    console.log(`> Integrated Server (Next.js + Socket.io) ready on http://${hostname}:${port}`)
    console.log(`> Socket.io path: /socket.io/`)
  })

  // Graceful shutdown
  process.on('SIGTERM', () => {
    console.log('Received SIGTERM signal, shutting down server...')
    httpServer.close(() => {
      console.log('Server closed')
      process.exit(0)
    })
  })

  process.on('SIGINT', () => {
    console.log('Received SIGINT signal, shutting down server...')
    httpServer.close(() => {
      console.log('Server closed')
      process.exit(0)
    })
  })
})
